// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Hello256World/trader-backend_monorepo/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewStrategiesRepositoryMock creates a new instance of StrategiesRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStrategiesRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StrategiesRepositoryMock {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &StrategiesRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// StrategiesRepositoryMock is an autogenerated mock type for the StrategiesRepository type
type StrategiesRepositoryMock struct {
	mock.Mock
}

type StrategiesRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StrategiesRepositoryMock) EXPECT() *StrategiesRepositoryMock_Expecter {
	return &StrategiesRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type StrategiesRepositoryMock
func (_mock *StrategiesRepositoryMock) GetByID(context1 context.Context, s string) (*domain.Strategy, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Strategy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Strategy, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Strategy); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Strategy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StrategiesRepositoryMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type StrategiesRepositoryMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *StrategiesRepositoryMock_Expecter) GetByID(context1 any, s any) *StrategiesRepositoryMock_GetByID_Call {
	return &StrategiesRepositoryMock_GetByID_Call{Call: _e.mock.On("GetByID", context1, s)}
}

func (_c *StrategiesRepositoryMock_GetByID_Call) Run(run func(context1 context.Context, s string)) *StrategiesRepositoryMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StrategiesRepositoryMock_GetByID_Call) Return(strategy *domain.Strategy, err error) *StrategiesRepositoryMock_GetByID_Call {
	_c.Call.Return(strategy, err)
	return _c
}

func (_c *StrategiesRepositoryMock_GetByID_Call) RunAndReturn(run func(context1 context.Context, s string) (*domain.Strategy, error)) *StrategiesRepositoryMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type StrategiesRepositoryMock
func (_mock *StrategiesRepositoryMock) Insert(context1 context.Context, strategy *domain.Strategy) (string, error) {
	ret := _mock.Called(context1, strategy)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Strategy) (string, error)); ok {
		return returnFunc(context1, strategy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Strategy) string); ok {
		r0 = returnFunc(context1, strategy)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Strategy) error); ok {
		r1 = returnFunc(context1, strategy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StrategiesRepositoryMock_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type StrategiesRepositoryMock_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - context1 context.Context
//   - strategy *domain.Strategy
func (_e *StrategiesRepositoryMock_Expecter) Insert(context1 any, strategy any) *StrategiesRepositoryMock_Insert_Call {
	return &StrategiesRepositoryMock_Insert_Call{Call: _e.mock.On("Insert", context1, strategy)}
}

func (_c *StrategiesRepositoryMock_Insert_Call) Run(run func(context1 context.Context, strategy *domain.Strategy)) *StrategiesRepositoryMock_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Strategy
		if args[1] != nil {
			arg1 = args[1].(*domain.Strategy)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StrategiesRepositoryMock_Insert_Call) Return(s string, err error) *StrategiesRepositoryMock_Insert_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *StrategiesRepositoryMock_Insert_Call) RunAndReturn(run func(context1 context.Context, strategy *domain.Strategy) (string, error)) *StrategiesRepositoryMock_Insert_Call {
	_c.Call.Return(run)
	return _c
}
